function generateinput(Rsvpstream,Lag)

% generates an input vector from an RSVP stream based on the parameters
%It uses the data structure generated by inputpatterns (which is passed in
%through the parameter Rsvpstream) as well as various global parameters to
%determine the time step by timestep resolution.

%Distractors are used in increasing order starting from item #11.
%T1 and T2 are always items 1 and 2.
global NUMINPUTS NUMITEMS
global Retina stepperlag itemperlag RespRetina delaystd
global T1BLANK T2BLANK T1BLANK2 FORWARDMASK NUMTARGS NUMDISTRACTORS
global genval genval2 keydistval skelmask Equalgens whichds skel onetarg respdistval resptargval respitemval

dist = 0;
FORWARDMASK = 0;
Retina = 0;
RespRetina = 0;

%SRIVAS
keytindex = 0;
resptindex = 0;

for (i = 1:NUMITEMS)
    if(Equalgens)    %when in a hurry, we test with T1 = T2
        genval2 = genval;
    end
    if(Rsvpstream(Lag,i,1))  %T1
        %genval = keyvals(ceil(rand * length(keyvals)));
        %disp(sprintf('Key feature strength %.3f', genval));
        val = genval;
    elseif(Rsvpstream(Lag,i,2))  %T2
        val = genval2;
    else   %distractors
        val = keydistval;
    end
    
    %special case if skeletal 1 target condition, then distractors are set to zero but we
    %wanna keep the T+1 item
    if skel && i > 1 && onetarg
        if (Rsvpstream(Lag,i-1,1)) %get the T1+1 item
            val = skelmask;
        end
    end
    
    %copy the items into the "retina"
    tempret = zeros(1,NUMINPUTS);
    tempret(1,1:2) = reshape(Rsvpstream(Lag,i,1:2),[1,2]) * val;  % copy the 2 items
    dodistractor = 1;

    %SRIVAS
    temprespret = zeros(1,NUMINPUTS);
    if Rsvpstream(Lag,i,4)
        if Rsvpstream(Lag,i,1) == 1
            temprespret(1,1) = resptargval;
        elseif Rsvpstream(Lag,i,2) == 1
            temprespret(1,2) = resptargval;
        end
    end

    if(Rsvpstream(Lag,i,3) == 2)  %are we doing a sequential distractor at this lag?
        if(i > 2 & i <= size(Rsvpstream,2))
            %Various blank conditions
            if(T1BLANK)   %T1 + 1 Blank
                if(~FORWARDMASK & (Rsvpstream(Lag,i-1,1)))
                    dodistractor = 0;
                end
                if(FORWARDMASK & (Rsvpstream(Lag,i+1,1)))
                    dodistractor = 0;
                end
            end
            if(T1BLANK2)   %T1 + 2 Blank
                if(~FORWARDMASK & (Rsvpstream(Lag,i-2,1)))
                    dodistractor = 0;
                end
                if(FORWARDMASK & (Rsvpstream(Lag,i+1,1)))
                    dodistractor = 0;
                end
            end
            if(T2BLANK)     %T2 +1-N Blank
                sum((Rsvpstream(Lag,1:i-1,2)) > 0);
                if(~FORWARDMASK & sum((Rsvpstream(Lag,1:i-1,2)) > 0))
                    dodistractor = 0;
                end
                if(FORWARDMASK & (Rsvpstream(Lag,i+1,2)))
                    dodistractor = 0;
                end
            end
        end

        %which distractor item is present in this slot of the RSVP stream
        %We reuse distractor items if we go beyond 10, starting at 1 again
        whichd = mod(dist,NUMDISTRACTORS) + 1 + NUMTARGS;
        if(dodistractor)
            tempret(1,whichd) = val;
            dist = dist + 1;
        end
        whichds(i) = whichd;

        %SRIVAS
        if Rsvpstream(Lag,i,4) == 1
            temprespret(1,whichd) = respitemval;
        elseif Rsvpstream(Lag,i,4) == 2
            temprespret(1,whichd) = respdistval;
        end
    end

    %SRIVAS
    randkeydelay = round(delaystd * randn);
    randrespdelay = randkeydelay;%round(delaystd * randn);
    
    for(j= 1: stepperlag+randkeydelay)   %now fill in the actual bits of items for each 5 ms timestep
        keytindex = keytindex + 1;
        if keytindex <= NUMITEMS * stepperlag
            Retina(keytindex,1:NUMINPUTS) = tempret;
        end
    end
    
    for(j= 1: stepperlag+randrespdelay)   %now fill in the actual bits of items for each 5 ms timestep
        resptindex = resptindex + 1;
        if resptindex <= NUMITEMS * stepperlag
            RespRetina(resptindex,1:NUMINPUTS) = temprespret;
        end
    end
end
